# Generated by Django 4.0.5 on 2022-06-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customermultipleproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermultipleproduct',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
